package iGuru.Sportsbook.BIP.Routes;

public class Token {
	//User Token
		// user = Viraj1
		public static String Utoken = "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdF9uYW1lIjoiSmFtZXMiLCJsYXN0X25hbWUiOiJOaWt3IiwidXNlcm5hbWUiOiJWaXJhajEiLCJlbWFpbCI6InZpcmFqMUB5b3BtYWlsLmNvbSIsImlkIjoxMDQsImlhdCI6MTY5MzU0MjY5NywiZXhwIjoxNjk2MjIxMDk3fQ.SlCqjkEpeXs_kezJ9AfZkHzDG36klewZxzW7vq_DCW4";
		// user = yash_kumbhani
		public static String Utoken1 = "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdF9uYW1lIjoieWFzaCIsImxhc3RfbmFtZSI6Ikt1bWJoYW5pIiwidXNlcm5hbWUiOiJ5YXNoX2t1bWJoYW5pIiwiZW1haWwiOiJ5YXNoLmt1bWJoYW5pMDFAZ21haWwuY29tIiwiaWQiOjE2LCJpYXQiOjE2OTQ0MDczMTUsImV4cCI6MTY5NzA4NTcxNX0.6iNPPVyUQWIM9TO4a1QaM9YXqTQ7V81JefYygWqiu4M";

		
		//Admin Token
		//Super Admin
		public static String super_admin = "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdF9uYW1lIjoic3VwZXIiLCJsYXN0X25hbWUiOiJhZG1pbiIsInVzZXJuYW1lIjoic3VwZXJfYWRtaW4iLCJlbWFpbCI6InN1cGVyYWRtaW5AZ21haWwuY29tIiwiaWQiOjEsImlhdCI6MTY5NDQwNzQyMSwiZXhwIjoxNjk3MDg1ODIxfQ.IgiJ5esbpsmWwcGYv2l-TKNDCtzJ1bjp92ogc3t1Mfo";
		
		//Cashier Login user= CT1
		public static String cashier= "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdF9uYW1lIjoiQyIsImxhc3RfbmFtZSI6IlQiLCJ1c2VybmFtZSI6IkNUMSIsImVtYWlsIjoiQ1QxQGluLmNvbSIsImlkIjo1NSwiaWF0IjoxNjkzODMyNzIwLCJleHAiOjE2OTY1MTExMjB9.lH1zicB7arbT6jfHEPYKlxWQvmWM6Dd59m7Hl46bA_8";

		// Cashier Login User= adminarka
		public static String adminarka = "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdF9uYW1lIjoiQXJrYSIsImxhc3RfbmFtZSI6IlNJbmhhIiwidXNlcm5hbWUiOiJhZG1pbmFya2EiLCJlbWFpbCI6ImFya2FAaWd1cnUtaW5kaWEuY29tIiwiaWQiOjIsImlhdCI6MTY5NDQwNzY1MSwiZXhwIjoxNjk3MDg2MDUxfQ.6i6I-W1Oxq5WbiFpXSumer914sUQpCzBBjx2T9ybcQw";
		
		// SuperVisor Login user = ST1
		public static String supervisor= "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdF9uYW1lIjoiV3lhdHQiLCJsYXN0X25hbWUiOiJQcmljZSIsInVzZXJuYW1lIjoiU1QxIiwiZW1haWwiOiJrb3hpa29oQG1haWxpbmF0b3IuY29tIiwiaWQiOjU2LCJpYXQiOjE2OTM5MDg3OTYsImV4cCI6MTY5NjU4NzE5Nn0.lVRYcRx29npb2-8NT2iZL_UNNeb-d7YwCphcmMtvsco";

		//Super visor login user= super
		public static String supervisor_admin= "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdF9uYW1lIjoiU3VwZXIiLCJsYXN0X25hbWUiOiJWaXNvciIsInVzZXJuYW1lIjoic3VwZXJ2aXNvcl9hZG1pbiIsImVtYWlsIjoic3VwZXJhZG1pbkBnbWFpbC5jb20iLCJpZCI6NSwiaWF0IjoxNjk0NDA3NzY3LCJleHAiOjE2OTcwODYxNjd9.BJoTZLrkbCsE2CvIKYJyUD9FblUf6WxHjVORexBIQTc";

}
