package iGuru.Sportsbook.BIP.Payload;

public class Menu_LeaguePayload {
	//Menu payload
	public static String getmenus = "{\r\n"
			+ "    \"name\":\"\",\r\n"
			+ "    \"slug\":\"\",\r\n"
			+ "    \"order_key\":\"id\", \r\n" //  id,name,slug,icon,action,created_at
			+ "    \"order_value\":\"ASC\" \r\n" //ASC, DESC
			+ "}";
	public static String addmenu = "{\r\n"
			+ "    \"name\":\"Dashboard1\",\r\n"
			+ "    \"slug\":\"dashboard\",\r\n"
			+ "    \"action\":\"view\",\r\n"
			+ "    \"icon\":\"monitor-dashboard\"\r\n"
			+ "}";

	public static String updatemenu="{\r\n"
			+ "    \"id\":1,\r\n"
			+ "    \"name\":\"Dashboard\",\r\n"
			+ "    \"slug\":\"dashboard\",\r\n"
			+ "    \"action\":\"view\",\r\n"
			+ "    \"icon\":\"monitor-dashboard\"\r\n"
			+ "}";
	
	//Role Payload
	public static String getroles = "{\r\n"
			+ "    \"role_id\":\"\",\r\n"
			+ "    \"status\":\"\",\r\n"
			+ "    \"name\":\"\",\r\n"
			+ "    \"order_key\":\"id\",\r\n"  // id,name,role_description,status,created_at
			+ "    \"order_value\":\"ASC\" \r\n" //ASC, DESC
			+ "}";
	public static String addrole = "{\r\n"
			+ "    \"role_id\":2,\r\n"
			+ "    \"access\":[\r\n"
			+ "        {\r\n"
			+ "            \"id\":7,\r\n"
			+ "            \"short_by\":\"view\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"id\":8,\r\n"
			+ "            \"short_by\":\"view\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"id\":9,\r\n"
			+ "            \"short_by\":\"view\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"id\":10,\r\n"
			+ "            \"short_by\":\"view\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"id\":11,\r\n"
			+ "            \"short_by\":\"view\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"id\":12,\r\n"
			+ "            \"short_by\":\"view\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"id\":13,\r\n"
			+ "            \"short_by\":\"view\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"id\":14,\r\n"
			+ "            \"short_by\":\"view\"\r\n"
			+ "        }\r\n"
			+ "    ]\r\n"
			+ "}";
	public static String updaterole="{\r\n"
			+ "   \"id\":2,\r\n"
			+ "   \"role_id\":2,\r\n"
			+ "    \"access\":[\r\n"
			+ "        {\r\n"
			+ "            \"id\":7,\r\n"
			+ "            \"short_by\":\"view\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"id\":8,\r\n"
			+ "            \"short_by\":\"view\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"id\":9,\r\n"
			+ "            \"short_by\":\"view\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"id\":10,\r\n"
			+ "            \"short_by\":\"view\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"id\":11,\r\n"
			+ "            \"short_by\":\"view\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"id\":12,\r\n"
			+ "            \"short_by\":\"view\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"id\":13,\r\n"
			+ "            \"short_by\":\"view\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"id\":14,\r\n"
			+ "            \"short_by\":\"view\"\r\n"
			+ "        }\r\n"
			+ "    ]\r\n"
			+ "}";
	
	//Permission Payload
	
	public static String getpermission="{\r\n"
			+ "    \"role_name\":\"\",\r\n"
			+ "    \"order_key\":\"id\",\r\n"  //  id,role_name,created_at
			+ "    \"order_value\":\"ASC\" \r\n" //ASC, DESC
			+ "}";
	public static String addpermission="{\r\n"
			+ "    \"role_id\":2,\r\n"
			+ "    \"access\":[\r\n"
			+ "        {\r\n"
			+ "            \"id\":7,\r\n"
			+ "            \"short_by\":\"view\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"id\":8,\r\n"
			+ "            \"short_by\":\"view\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"id\":9,\r\n"
			+ "            \"short_by\":\"view\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"id\":10,\r\n"
			+ "            \"short_by\":\"view\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"id\":11,\r\n"
			+ "            \"short_by\":\"view\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"id\":12,\r\n"
			+ "            \"short_by\":\"view\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"id\":13,\r\n"
			+ "            \"short_by\":\"view\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"id\":14,\r\n"
			+ "            \"short_by\":\"view\"\r\n"
			+ "        }\r\n"
			+ "    ]\r\n"
			+ "}";
	public static String updatepermission="{\r\n"
			+ "   \"id\":2,\r\n"
			+ "   \"role_id\":2,\r\n"
			+ "    \"access\":[\r\n"
			+ "        {\r\n"
			+ "            \"id\":7,\r\n"
			+ "            \"short_by\":\"view\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"id\":8,\r\n"
			+ "            \"short_by\":\"view\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"id\":9,\r\n"
			+ "            \"short_by\":\"view\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"id\":10,\r\n"
			+ "            \"short_by\":\"view\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"id\":11,\r\n"
			+ "            \"short_by\":\"view\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"id\":12,\r\n"
			+ "            \"short_by\":\"view\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"id\":13,\r\n"
			+ "            \"short_by\":\"view\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"id\":14,\r\n"
			+ "            \"short_by\":\"view\"\r\n"
			+ "        }\r\n"
			+ "    ]\r\n"
			+ "}";
	//Shop payload
	public static String getshops = "{\r\n"
			+ "    \"name\":\"\",\r\n"
			+ "    \"contact_number\":\"\",\r\n"
			+ "    \"order_key\":\"user.username\", \r\n" // id,name,country_code,contact_number,address,user.username,created_at
			+ "    \"order_value\":\"ASC\" \r\n" //ASC, DESC
			+ "}";
	
	public static String addshops = "{\r\n"
			+ "    \"name\":\"Yash Shop\",\r\n"
			+ "    \"country_code\":\"91\",\r\n"
			+ "    \"contact_number\":\"7878454512\",\r\n"
			+ "    \"address\":\"survey no. 124, Nr. aashirwad textiles, -380021\"\r\n"
			+ "}";
	public static String updateshops = "{\"id\":19,\r\n"
			+ "    \"name\":\"Bet Shop 5\",\r\n"
			+ "    \"country_code\":\"91\",\r\n"
			+ "    \"contact_number\":\"7878454519\",\r\n"
			+ "    \"address\":\"survey no. 1250, Nr. aashirwad textiles, -380021\"}";
	
	public static String shopassign ="{\r\n"
			+ "    \"shop_id\":2,\r\n"
			+ "    \"admin_users\" : [\r\n"
			+ "         { \"role_id\":2,\"admin_user_id\":14},\r\n"
			+ "         { \"role_id\":3,\"admin_user_id\":3}\r\n"
			+ "    ]\r\n"
			+ "}";
	
	//User payload
	public static String getusers = "{\r\n"
			+ "    \"search\":\"\",\r\n"
			+ "    \"status\":\"\",\r\n"
			+ "    \"order_key\":\"id\", \r\n" // id,username,first_name,last_name,email,country_code,phone,balance,status,created_at
			+ "    \"order_value\":\"ASC\" \r\n" //ASC, DESC
			+ "}";
	
	public static String addusers = "{\r\n"
			+ "    \"first_name\":\"Nimish\",\r\n"
			+ "    \"last_name\":\"Bhuava\",\r\n"
			+ "    \"username\":\"nimish_bhuva\",\r\n"
			+ "    \"password\":\"Abcd@1234\",\r\n"
			+ "    \"email\":\"nimish123@gmail.com\",\r\n"
			+ "    \"country_code\":\"91\",\r\n"
			+ "    \"dob\":\"2000-11-26\",\r\n"
			+ "    \"phone\":\"9999988811\",\r\n"
			+ "    \"balance\":0,\r\n"
			+ "    \"status\":\"1\",\r\n"
			+ "    \"address\":\"Shapath IV, 502 - A, Sarkhej - Gandhinagar Hwy, opp. Karnavati Club, Prahlad Nagar\"\r\n"
			+ "}";
	public static String updateusers = "{\r\n"
			+ "    \"id\":5,\r\n"
			+ "    \"first_name\":\"Vivek\",\r\n"
			+ "    \"last_name\":\"Bhuva\",\r\n"
			+ "    \"username\":\"vivek123\",\r\n"
			+ "    \"password\":\"Abcd@1234\",\r\n"
			+ "    \"email\":\"vivek.bhuva@gmail.com\",\r\n"
			+ "    \"country_code\":\"91\",\r\n"
			+ "    \"dob\":\"2000-11-26\",\r\n"
			+ "    \"phone\":\"7698248376\",\r\n"
			+ "    \"balance\":100,\r\n"
			+ "    \"status\":\"1\",\r\n"
			+ "    \"address\":\"Shapath IV, 502 - A, Sarkhej - Gandhinagar Hwy, opp. Karnavati Club, Prahlad Nagar\"\r\n"
			+ "}";
	
	//Admin User
	public static String getadminusers = "{\r\n"
			+ "    \"search\":\"\",\r\n"
			+ "    \"role_id\":\"\",\r\n"
			+ "    \"order_key\":\"id\", \r\n" // id,username,first_name,last_name,email,country_code,phone,balance,role.name,created_at
			+ "    \"order_value\":\"ASC\" \r\n" //ASC, DESC
			+ "}";
	
	public static String addadminuser = "{\r\n"
			+ "    \"first_name\":\"yash\",\r\n"
			+ "    \"last_name\":\"cashier\",\r\n"
			+ "    \"username\":\"yash_kumbhani\",\r\n"
			+ "    \"password\":\"Abcd@1234\",\r\n"
			+ "    \"email\":\"yashcashier@gmail.com\",\r\n"
			+ "    \"dob\":\"2000-11-26\",\r\n"
			+ "    \"country_code\":\"91\",\r\n"
			+ "    \"phone\":\"7698248110\",\r\n"
			+ "    \"role_id\":2,\r\n"
			+ "    \"balance\":0,\r\n"
			+ "    \"vat_number\":\"\",\r\n"
			+ "    \"address\":\"Shapath IV, 502 - A, Sarkhej - Gandhinagar Hwy, opp. Karnavati Club, Prahlad Nagar\"\r\n"
			+ "}";
	public static String updateadminuser = "{\r\n"
			+ "    \"id\":5,\r\n"
			+ "    \"first_name\":\"nikunj\",\r\n"
			+ "    \"last_name\":\"kumar\",\r\n"
			+ "    \"username\":\"nikunj_kumbhani\",\r\n"
			+ "    \"password\":\"Abcd@1234\",\r\n"
			+ "    \"email\":\"yash.kumbhani@gmail.com\",\r\n"
			+ "    \"dob\":\"2000-11-27\",\r\n"
			+ "    \"country_code\":\"91\",\r\n"
			+ "    \"phone\":\"7698248345\",\r\n"
			+ "    \"role_id\":5,\r\n"
			+ "    \"balance\":10.02,\r\n"
			+ "    \"vat_number\":\"\",\r\n"
			+ "    \"address\":\"Shapath IV, 502 - A, Sarkhej - Gandhinagar Hwy, opp. Karnavati Club, Prahlad Nagar\"\r\n"
			+ "}";
	
	//System Setting
	public static String updatesystemsetting = "{\r\n"
			+ "    \"settings\":[\r\n"
			+ "        {\r\n"
			+ "            \"id\":1,\r\n"
			+ "            \"value\":15\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"id\":2,\r\n"
			+ "            \"value\":1000\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"id\":3,\r\n"
			+ "            \"value\":15\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"id\":4,\r\n"
			+ "            \"value\":10\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"id\":5,\r\n"
			+ "            \"value\":0\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"id\":6,\r\n"
			+ "            \"value\":0\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"id\":7,\r\n"
			+ "            \"value\":0\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"id\":8,\r\n"
			+ "            \"value\":0\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"id\":9,\r\n"
			+ "            \"value\":0\r\n"
			+ "        }\r\n"
			+ "    ]\r\n"
			+ "}";
	
	//Leagues
	public static String getleagues = "{\r\n"
			+ "    \"search\":\"\"\r\n"
			+ "}";
	public static String updateleague = "{\r\n"
			+ "    \"top_leagues\":[211]\r\n"
			+ "}";
}
